"""autogenerated by genpy from quad_status/Status.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy
import std_msgs.msg

class Status(genpy.Message):
  _md5sum = "3563f39c50382b772e10b44ffe9cb2ed"
  _type = "quad_status/Status"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header
float32 Batt_Voltage
bool RC_OK
bool Motors_ON
bool ExCtrl_ON
duration Run_Time

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.secs: seconds (stamp_secs) since epoch
# * stamp.nsecs: nanoseconds since stamp_secs
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

"""
  __slots__ = ['header','Batt_Voltage','RC_OK','Motors_ON','ExCtrl_ON','Run_Time']
  _slot_types = ['std_msgs/Header','float32','bool','bool','bool','duration']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,Batt_Voltage,RC_OK,Motors_ON,ExCtrl_ON,Run_Time

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Status, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.Batt_Voltage is None:
        self.Batt_Voltage = 0.
      if self.RC_OK is None:
        self.RC_OK = False
      if self.Motors_ON is None:
        self.Motors_ON = False
      if self.ExCtrl_ON is None:
        self.ExCtrl_ON = False
      if self.Run_Time is None:
        self.Run_Time = genpy.Duration()
    else:
      self.header = std_msgs.msg.Header()
      self.Batt_Voltage = 0.
      self.RC_OK = False
      self.Motors_ON = False
      self.ExCtrl_ON = False
      self.Run_Time = genpy.Duration()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_f3B2i.pack(_x.Batt_Voltage, _x.RC_OK, _x.Motors_ON, _x.ExCtrl_ON, _x.Run_Time.secs, _x.Run_Time.nsecs))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.Run_Time is None:
        self.Run_Time = genpy.Duration()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 15
      (_x.Batt_Voltage, _x.RC_OK, _x.Motors_ON, _x.ExCtrl_ON, _x.Run_Time.secs, _x.Run_Time.nsecs,) = _struct_f3B2i.unpack(str[start:end])
      self.RC_OK = bool(self.RC_OK)
      self.Motors_ON = bool(self.Motors_ON)
      self.ExCtrl_ON = bool(self.ExCtrl_ON)
      self.Run_Time.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_f3B2i.pack(_x.Batt_Voltage, _x.RC_OK, _x.Motors_ON, _x.ExCtrl_ON, _x.Run_Time.secs, _x.Run_Time.nsecs))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.Run_Time is None:
        self.Run_Time = genpy.Duration()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 15
      (_x.Batt_Voltage, _x.RC_OK, _x.Motors_ON, _x.ExCtrl_ON, _x.Run_Time.secs, _x.Run_Time.nsecs,) = _struct_f3B2i.unpack(str[start:end])
      self.RC_OK = bool(self.RC_OK)
      self.Motors_ON = bool(self.Motors_ON)
      self.ExCtrl_ON = bool(self.ExCtrl_ON)
      self.Run_Time.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3I = struct.Struct("<3I")
_struct_f3B2i = struct.Struct("<f3B2i")
